### ISSUE TITLE
OSS License

### ISSUE THREAD

**Issue by atinfinity** [NeelBit/menu-colapsable-en-vue3#1]
@NeelBit I'm interested in this project. On the other hands, there is no license in this repository.
So, I check the document of GitHub.
<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository>

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

If you possible, I hope that you include an OSS license.

**Comment by NeelBit** [comment]
Hola, @atinfinity, perdón por responder en español; el repositorio consta de un ejercicio guiado y escrito por otra persona, en el archivo readme puedes ver el enlace al vídeo para mas información. De todas maneras, y sin mucho conocimiento sobre eso, le añadí una licencia GPL 2.0. Gracias por la recomendación/sugerencia, saludos.

**Comment by atinfinity** [comment]
@NeelBit Gracias por la rápida respuesta.
